# Motion Simulator version 1.0

**Ver 1:**

- Implement the input section (see plan on OneNote)
- Implement the Processing (see plan on OneNote)
- Output: print out the array of points 

In [1]:
# Import libraries

# Numerical Python - Library for fast numerical vector and matrix calculations
import numpy as np

## Input

In [2]:
# Set the numer of time steps
N = 100

# Set the time step
dt = 0.1

# Define function for 2D trajectory
# Input: - time t
# output: - position vector at time t 
def trajectory(t):
    # linear motion with velocity (1,1)
    return np.array([t,t])


##  Processing

In [3]:
# Initialise variables
t = 0
points = np.zeros((N+1,2))

# Calculate the N points on the trajectory for times with a time step dt apart
for i in range(N+1):
  # call function trajectory with time t
  points[i] = trajectory(t)
  # save the new point in array points
  # update the time by the time step
  t += dt

## Output

In [4]:
print(points)

[[ 0.   0. ]
 [ 0.1  0.1]
 [ 0.2  0.2]
 [ 0.3  0.3]
 [ 0.4  0.4]
 [ 0.5  0.5]
 [ 0.6  0.6]
 [ 0.7  0.7]
 [ 0.8  0.8]
 [ 0.9  0.9]
 [ 1.   1. ]
 [ 1.1  1.1]
 [ 1.2  1.2]
 [ 1.3  1.3]
 [ 1.4  1.4]
 [ 1.5  1.5]
 [ 1.6  1.6]
 [ 1.7  1.7]
 [ 1.8  1.8]
 [ 1.9  1.9]
 [ 2.   2. ]
 [ 2.1  2.1]
 [ 2.2  2.2]
 [ 2.3  2.3]
 [ 2.4  2.4]
 [ 2.5  2.5]
 [ 2.6  2.6]
 [ 2.7  2.7]
 [ 2.8  2.8]
 [ 2.9  2.9]
 [ 3.   3. ]
 [ 3.1  3.1]
 [ 3.2  3.2]
 [ 3.3  3.3]
 [ 3.4  3.4]
 [ 3.5  3.5]
 [ 3.6  3.6]
 [ 3.7  3.7]
 [ 3.8  3.8]
 [ 3.9  3.9]
 [ 4.   4. ]
 [ 4.1  4.1]
 [ 4.2  4.2]
 [ 4.3  4.3]
 [ 4.4  4.4]
 [ 4.5  4.5]
 [ 4.6  4.6]
 [ 4.7  4.7]
 [ 4.8  4.8]
 [ 4.9  4.9]
 [ 5.   5. ]
 [ 5.1  5.1]
 [ 5.2  5.2]
 [ 5.3  5.3]
 [ 5.4  5.4]
 [ 5.5  5.5]
 [ 5.6  5.6]
 [ 5.7  5.7]
 [ 5.8  5.8]
 [ 5.9  5.9]
 [ 6.   6. ]
 [ 6.1  6.1]
 [ 6.2  6.2]
 [ 6.3  6.3]
 [ 6.4  6.4]
 [ 6.5  6.5]
 [ 6.6  6.6]
 [ 6.7  6.7]
 [ 6.8  6.8]
 [ 6.9  6.9]
 [ 7.   7. ]
 [ 7.1  7.1]
 [ 7.2  7.2]
 [ 7.3  7.3]
 [ 7.4  7.4]
 [ 7.5  7.5]
 [ 7.6  7.6]

## Test

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
np.zeros((100,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [23]:
points[1]

29.900000000000155

In [25]:
points?

Type:            ndarray
String form:     [29.9 29.9]
Length:          2
File:            c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created 

In [29]:
points[0]

array([0., 0.])